### ISSUE TITLE
multiple issues (current : a problem with .bdl files ?)

### ISSUE THREAD

**Issue by ireallyneedhelpp** [niacdoial/blemd#15]
it tells me there is an error with the line temp = bmodel.bmodel() and also that bmodel is not defined.
i am working on version 2.79

**Comment by niacdoial** [comment]
Hello,
Sorry for the late response, but I think you are not using the latest
version of the import script (IOManager.py).
You will probably have to download and install the latest version of the
whole add-on too.
the batch file (converter.bat) didn't change, so you won't need to
re-download and re-edit it, though.

Have a nice day!

PS: I still needed to fix another bug, that was in the "latest" version
before this mail, but different from the bug you spotted.
It is fixed now.

2018-03-15 22:32 GMT+01:00 ireallyneedhelpp <notifications@github.com>:

**Comment by ireallyneedhelpp** [comment]
i downloaded it again and still get the same error
![picture](https://user-images.githubusercontent.com/37421646/37921334-6e2669e8-3121-11e8-92c5-da18e94078c9.PNG)

**Comment by niacdoial** [comment]
Oh.
Er... Okay now it should be actually fixed.
Sorry, but for some reason I thought you were using the converter batch (a small script which runs blender in the background and outputs a fbx model)
That also means that my previous reply was wrong (you probably actually had the up-to-date version at the time) and probably really confusing. And somewhat rude. Sorry for that.
Thanks for your patience.

**Comment by ireallyneedhelpp** [comment]
![capture](https://user-images.githubusercontent.com/37421646/38465421-58794420-3b13-11e8-8739-463dbf5652d7.PNG)
i downloaded the newest version and now i get this message, sorry for being such an inconvenience.

**Comment by niacdoial** [comment]
A couple of things here:
**1 :** The error you have means that it didn't find the `"bmdview.exe"` file (used to extract the images), that was supposed to be next to the other `'.py'` files. Meaning that either it is really missing, or it wasn't looking in the right place. I'll look for potential causes of the second.
**2 :** I saw the previous version of your message, and the error in this version happens before the error of the previous version even has a chance to.  It probably has more meaning for you than for me, though.
**3 :** The error of the previous version *is* now sort of fixed. What it meant is that a part of the file cannot be understood by the addon (and I doubt it will be in the near future). Instead of crashing like an idiot, the addon will now ignore this part to focus on what can be imported. This means, however, that the final mesh might be incomplete, in ways I literally know nothing about.
BTW, could I ask you to give me a copy of the file that triggered the "unknown mdl3 entry" error, please?

**Comment by ireallyneedhelpp** [comment]
so i downloaded it again and now the import process works and i actually get an output, however the textures are messed up and its all 1 object. is this how its supposed to be or am i missing a step or something.
thanks for your help so far and sorry for being an inconvenience
### and i dont know what "unkown mdl3 entry" is or the file that caused it

**Comment by niacdoial** [comment]
*About the "one object" problem* : I don't think this problem can ever be solved, because while the model stored inside the `bmd` file is divided between smaller parts, the the way it is done does rarely makes sense (at least for static elements).
![wrong parts](https://user-images.githubusercontent.com/17071037/38829894-d793f504-41ba-11e8-976b-2de20fe38fc5.jpg)

*About the texture problem* : if the texture looks looks a corrupted mess (a bit like this : http://dreamstime.com/stock-photo-glitch-texture-data-colorful-chaos-image59140534) it might be because the BMD file does not contain the texture, but refers to it. Sadly, I haven't looked that much into this.
If it looks like something decent, but badly stretched, crumpled, or simply in the wrong place, it may actually be a bug, but it is also likely because the texture was supposed to be animated, and I haven't found a way to translate texture animations to blender.
Checking the "use complete materials" options might also help (bottom left when you choose the file to import).
I might be able to be more precise with a screenshot of the problem (Not now though. See the end of the message)

*The mdl3 error* was the error reported by the first version of your previous post. I should have been more clear on that point. sorry.

*Last but not least : * you are not being an inconvenience. At all.
During this discussion, you found no less than three different bugs, and when there was no bug, what you found was something I wasn't clear enough about.

Also, a little heads-up: I will likely not be able to do anything here in the next couple weeks or so, so I hope it works enough for you.
In the meantime, have a nice day!

**Comment by ireallyneedhelpp** [comment]
i was messing around with the addon and i found out that the problem with the one object can easily be fixed just by separating the model by loose parts(even though it could potentially creates hundreds of objects) and the texture issue, some models work properly with textures but others for example gobblegut from smg2 only have 2 textures with it.

**Comment by hisprofile** [comment]
MDL3 is only mentioned in .bdl files, that also contain objects like .bmd files. This happened to me when I changed the .bdl file extension to .bmd. It still works and can be read properly, but BMDView2 and your addon just doesn't know what to do with it.

**Comment by hisprofile** [comment]
Just tested it: changing .bdl to .bmd will work, but you may have to reapply the textures.

**Comment by hisprofile** [comment]
Sure thing: [
[bdl.zip](https://github.com/niacdoial/blemd/files/2195143/bdl.zip)

**Comment by niacdoial** [comment]
Thanks!
I looked at the file, and I already have a few ideas about what went wrong.
I have also changed the documentation, so a bunch of things should be easier to understand now.

**Comment by niacdoial** [comment]
Turns out, the problems with this particular bdl file are problems that could also happen with any bmd file.
I fixed them, and added a couple measures to better handle anything similar to one of them.
I still have to examine the bdl-specific 'mdl3' section, though.

**Comment by hisprofile** [comment]
Alright.

**Comment by hisprofile** [comment]
Hey, do you think you'll be able to add support for .bdl?

**Comment by niacdoial** [comment]
I mean, from what I have seen (this one model), there is, I just need to
make BleMD accept this file extension.
I still don't know what to make of this mdl3 part, though. So I guess it
means the result is not yet "guaranteed".

**Comment by hisprofile** [comment]
Btw, heres a website. Might help with mdl3


http://wiki.tockdom.com/wiki/BMD_and_BDL_(File_Format)

**Comment by niacdoial** [comment]
Thanks, but this wiki page does not have the info I was looking for.
Actually, there is a lot of missing sections in it.

On another note, I will be uploading the changes necessary to open .bdl
files shortly.

**Comment by hisprofile** [comment]
Oh sweet

**Comment by niacdoial** [comment]
Well, the current version is able to open both types if files, now.
It just cannot use the data from the mdl3 section, which, as far as I can
tell, can only affect the materials, and the current result doesn't look
broken in any way.
